### ISSUE TITLE
Detect file arrival based on timestamp

### ISSUE THREAD

**Issue by channing-jackson** [spring-cloud-stream-app-starters/sftp#3]
As a user of the SFTP source app, I would like to be able to configure the SFTP source so it polls the remote directory for file arrival based on a file with the same name, but a newer timestamp than the last one that was dropped.  According to the documentation and some preliminary testing, that does not seem to be an option.

**Comment by artembilan** [comment]
To be honest I don't understand what you mean.
Would you mind to re-phrase your concern somehow?

Maybe some sample with pseudo code?

The polling logic is based on the trigger options. Then we filter remote files and afterwards local files.

Thanks

**Comment by channing-jackson** [comment]
Sure.  Our use case is one where the provider of the file-based data drops a file of an identical name in the SFTP location each time.  Let's say `data.csv`. 

In my preliminary testing, if I set the filename pattern to find that file, it will load the first occurrence of that file just fine.  However, if I overwrite that `data.csv` file with a newer version, with different contents, my SFTP source is not detecting that it needs to load a new file.  It appears it is *only* using filename pattern matching criteria, and it is not paying attention to the fact that even though the filename is the same, the timestamp of the file itself is newer than the one it previously loaded. 

Does that make sense?

**Comment by artembilan** [comment]
Yep! It does.

So, your concern bumps to the fact of:
```
private volatile FileListFilter<File> localFileListFilter = new AcceptOnceFileListFilter<File>();
```
by default.
Which must be `FileSystemPersistentAcceptOnceFileListFilter`.
Plus `preserveTimestamp` should be configured.

Unfortunately we don't expose `localFilter` option. And I'm afraid you don't have any choice unless copy/paste `SftpSourceConfiguration` and inject that `FileSystemPersistentAcceptOnceFileListFilter`.

We probably can make it as default there because it doesn't have difference with the `AcceptOnceFileListFilter`, unless `preserveTimestamp` is configured.

**Comment by channing-jackson** [comment]
Well, that's the other thing.  It seems as though `preserveTimestamp` is not actually working as intended.  If I set that value to true, I'm still getting a File 'ref' object with a new timestamp instead of the one from the remote file system.

**Comment by artembilan** [comment]
Not sure how that can be possible - `AbstractInboundFileSynchronizer`:
```
File localFile = new File(localDirectory, localFileName);
if (!localFile.exists()) {
....
    if (this.preserveTimestamp) {
	localFile.setLastModified(getModified(remoteFile));
    }
}
```

**Comment by channing-jackson** [comment]
Ok.  Weird.  I will double check that and get back to you.

**Comment by channing-jackson** [comment]
Hey there.  So I saw that you marked this as an enhancement.  I'm guessing that means this will be available as an OOTB feature in upcoming releases? 

Had a follow-up question, though, about the preserveTimestamp setting.  Firstly, a correction.  I mentioned we were pulling the file as 'ref', but actually we are using 'contents' as the config choice there.  I'm sort of assuming the preserveTimestamp setting is like the "-p" switch one would use on an scp command, where the timestamp on the local file would reflect the timestamp on the remote file once transferred.  I'm wondering whether preserveTimestamp applies in the 'contents' mode?  In your code snippet above, is the localFile being written to a tempdir regardless of the transfer mode of the file itself (ref, line, contents)?

**Comment by artembilan** [comment]
Hello, @channing-jackson !

Thank you for reaching us back!

Well, yes, I think that `timestamp` manipulation should be as an out-of-the-box feature. It doesn't hurt by default. 
Only the problem that I've faced a blockage: the remote file modification doesn't have affect for local file because of:
```
File localFile = new File(localDirectory, localFileName);
if (!localFile.exists()) {
```
So, even if we make `FileSystemPersistentAcceptOnceFileListFilter` as a default filter, we can't reach it via remote file modification without local file deletion.

Now we are thinking about the proper solution. One of them is like: https://jira.spring.io/browse/INT-4231.

But that all means that the fix won't be available until the next release, not the current.

No, `preserveTimestamp` doesn't have effect for the `mode`. It is done already after `SftpInboundFileSynchronizingMessageSource` has returned a message with the `File` as `payload`.
So, independently of the `mode` you can use that logic based on timestamp.
But yeah... You have to remove local files somehow...

**Comment by artembilan** [comment]
See https://jira.spring.io/browse/INT-4232 for the particular problem.

**Comment by channing-jackson** [comment]
That is an interesting problem, to be sure.  And in our PCF environment, we are making an assumption that when we write a local file, we are writing it to a tmpdir (`System("java.io.tmpdir")`) because we aren't really depending on the existence of a file system.  Inherently, then, that physical file object is ephemeral.  It will get cleaned up once the tmpdir is cleaned up, depending on how that is configured.  Likewise, when we use the `contents` transfer mode, we assume we have no physical file, because we've read the contents of the file into a byte array, and we don't particularly care whether we have a physical file to deal with...

...until we decide to output that file data somewhere else -- potentially using an SFTP sink.  In that case, we might have a processor app upstream that writes the file(s), and then we want to pass the file(s) location to the SFTP sink, and have the sink pick them up and deliver them to the SFTP destination.  

The whole stream EL might be simplified to look like this: 
`sftp | transform | file-processor | sftp`

Each stream app seems to get its own container in which it runs, so even though the default `System("java.io.tmpdir")` location represents the same path (`/home/vcap/tmp`) that might not actually be the same physical path for another app in the stream.  

This seems to be becoming a larger question in general, so if this thread isn't the correct place to hold the discussion, I'm fine with moving it or taking it offline.  But it seems like if I want to pass file data through a stream of apps in a Spring Cloud Data Flow context, for example, we have to have a common TMPDIR file area where all apps can access that file data, even if they're in a different container.  I'm starting to wonder how practical the use of any file-based app is in this environment if I do not have a physical file system I can depend on.  Does this have to do with the configuration of my specific PCF environment, or would this be an issue in any PCF environment?  My understanding was that "cloud native" should be taken to mean that (among other things) you must develop applications without reliance on a physical file system.

**Comment by artembilan** [comment]
Thank you for sharing your mind, @channing-jackson !

Well, actually we are good aware of those distributed "cloud native" environment and this "local file" dilemma.  

I'm not familiar with the PCF, but seems for me I heard from my colleagues that there is something like shared file system. @sabbyanandan may know better how customers deal with the issue.

OTOH we have plan to introduce #2 - using `SftpStreamingMessageSource` which just place an `InputStream` of the remote file into `payload`. That part can be streamed to the `byte[]` in the memory and sent farther in the SCSt flow.

But anyway that seems for me that shared filesystem should be enabled somehow.
Although that is what (S)FTP is for...

**Comment by sabbyanandan** [comment]
@channing-jackson: The physical drive backed within the application container is ephemeral and it will _not_ be shared with other applications. It is transient and if the application crashes, a new container is spawned with the application running on it - a new ephemeral storage comes with it. This is the general platform behavior.

The streaming solution suggested by @artembilan (via #2) provides an alternative by directly streaming the file fragments in memory as opposed to downloading it to the local drive and re-processing. 

If you do have tight requirements to process files from a common shared disk, but with many applications, you could potentially take advantage of ["Volume Services"](https://docs.pivotal.io/pivotalcf/1-8/services/volume-services-v2.10.html). This has been [GA'd since PCF 1.8](https://docs.cloudfoundry.org/devguide/services/using-vol-services.html). There are a few [volume plugins](https://github.com/cloudfoundry-incubator/nfs-volume-release) supported with this service; however, we do not have enough visibility into the development/roadmap. I'd recommend engaging directly with PCF product teams.

**Comment by garyrussell** [comment]
Slightly tangential, but perhaps (in streaming mode) we should put file info (modified timestamp, size, permissions) into message headers. We currently only set remote directory (and filename) headers.

Maybe we could just dump the (S)FtpFileInfo object into a header.

**Comment by artembilan** [comment]
That is good idea, @garyrussell !

But I'm afraid we will end up with something like `fileInfoJson` instead of classpath-dependant `FtpFileInfo` entity in the headers.

I think together with the `JsonPropertyAccessor` we would have a good expressions to get access to target file properties.
